import type {Metadata} from "next";
import React from "react";

export const metadata: Metadata = {
    title: "PostIdLayout metadata",
    description: "Generated by create next app",
};
type Props = {
    children: React.ReactNode;
}
export default function PostIdLayout({children}: Props) {
    return (
        <div className={'bg-red-200 flex justify-center'}>
            Post Id Layout
        {children}
        </div>
    );
}
